#ifndef SWALLOW_COMPILER_DIAGNOSTICS_CODE_HPP
#define SWALLOW_COMPILER_DIAGNOSTICS_CODE_HPP

#include <cstdint>
namespace swallow::compiler::diagnostics
{

  enum Code : uint32_t
  {
    UNKNOWN,
    PARSING,
    LID_NOT_DECLARED,
    UID_NOT_DECLARED,
    EXPR_TYPE_CHECKING_FAILED,
    BINOP_NOT_DECLARED,
    BINOP_TYPE_MISMATCH,
    APPLICATION_TYPE_MISMATCH,
    MATCH_EXPR_TYPE_CHECKING_FAILED,
    MATCH_EXPR_BRANCHE_TYPE_CONFLICTS,
    PATTERN_CONSTRUCTOR_IS_NOT_FUNCTION,
    PATTERN_MISMATCH,
    FUNCTION_BODY_TYPE_CHECKING_FAILED,
    CONSTRUCTOR_NOT_DECLARED
  };

}

#endif /* SWALLOW_COMPILER_DIAGNOSTICS_CODE_HPP */